name: parking-lot
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 1234:5432
    expose:
      - 1234
    volumes:
      - ./data:/var/lib/postgresql/data

  maven:
    image: maven:3.9.5
    volumes:
      - ./server:/server
    working_dir: /server
    command: mvn clean install -Dmaven.test.skip=true

  backend:
    image: openjdk:21
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
    working_dir: /server/target
    command: java -jar server-0.0.1-SNAPSHOT.jar
    depends_on:
      maven:
        condition: service_completed_successfully
    